[package]
name = "screentime"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
local-ip-address = "0.6.3"
postgres = "0.19.10"
tiny_http = "0.12.0"

[features]
server = []
client = []
